/**
 * FROZEN BASE-GAME BOARD TOPOLOGY — generated by scripts/freeze-board.ts.
 * Do not edit by hand. Regenerate with `npm run freeze-board` (shared package),
 * then re-run the verification tests before trusting the result.
 */
import type { BoardTopology } from './types.js';

export const BOARD_DATA: BoardTopology = {
  "tiles": [
    {
      "id": 0,
      "axial": {
        "q": -2,
        "r": 0
      },
      "center": {
        "x": -207.85,
        "y": 0
      },
      "vertices": [
        0,
        1,
        2,
        3,
        4,
        5
      ],
      "edges": [
        0,
        1,
        2,
        3,
        4,
        5
      ]
    },
    {
      "id": 1,
      "axial": {
        "q": -2,
        "r": 1
      },
      "center": {
        "x": -155.88,
        "y": 90
      },
      "vertices": [
        6,
        7,
        8,
        9,
        2,
        1
      ],
      "edges": [
        6,
        7,
        8,
        9,
        1,
        10
      ]
    },
    {
      "id": 2,
      "axial": {
        "q": -2,
        "r": 2
      },
      "center": {
        "x": -103.92,
        "y": 180
      },
      "vertices": [
        10,
        11,
        12,
        13,
        8,
        7
      ],
      "edges": [
        11,
        12,
        13,
        14,
        7,
        15
      ]
    },
    {
      "id": 3,
      "axial": {
        "q": -1,
        "r": -1
      },
      "center": {
        "x": -155.88,
        "y": -90
      },
      "vertices": [
        14,
        15,
        0,
        5,
        16,
        17
      ],
      "edges": [
        16,
        17,
        5,
        18,
        19,
        20
      ]
    },
    {
      "id": 4,
      "axial": {
        "q": -1,
        "r": 0
      },
      "center": {
        "x": -103.92,
        "y": 0
      },
      "vertices": [
        18,
        19,
        6,
        1,
        0,
        15
      ],
      "edges": [
        21,
        22,
        10,
        0,
        17,
        23
      ]
    },
    {
      "id": 5,
      "axial": {
        "q": -1,
        "r": 1
      },
      "center": {
        "x": -51.96,
        "y": 90
      },
      "vertices": [
        20,
        21,
        10,
        7,
        6,
        19
      ],
      "edges": [
        24,
        25,
        15,
        6,
        22,
        26
      ]
    },
    {
      "id": 6,
      "axial": {
        "q": -1,
        "r": 2
      },
      "center": {
        "x": 0,
        "y": 180
      },
      "vertices": [
        22,
        23,
        24,
        11,
        10,
        21
      ],
      "edges": [
        27,
        28,
        29,
        11,
        25,
        30
      ]
    },
    {
      "id": 7,
      "axial": {
        "q": 0,
        "r": -2
      },
      "center": {
        "x": -103.92,
        "y": -180
      },
      "vertices": [
        25,
        26,
        14,
        17,
        27,
        28
      ],
      "edges": [
        31,
        32,
        20,
        33,
        34,
        35
      ]
    },
    {
      "id": 8,
      "axial": {
        "q": 0,
        "r": -1
      },
      "center": {
        "x": -51.96,
        "y": -90
      },
      "vertices": [
        29,
        30,
        18,
        15,
        14,
        26
      ],
      "edges": [
        36,
        37,
        23,
        16,
        32,
        38
      ]
    },
    {
      "id": 9,
      "axial": {
        "q": 0,
        "r": 0
      },
      "center": {
        "x": 0,
        "y": 0
      },
      "vertices": [
        31,
        32,
        20,
        19,
        18,
        30
      ],
      "edges": [
        39,
        40,
        26,
        21,
        37,
        41
      ]
    },
    {
      "id": 10,
      "axial": {
        "q": 0,
        "r": 1
      },
      "center": {
        "x": 51.96,
        "y": 90
      },
      "vertices": [
        33,
        34,
        22,
        21,
        20,
        32
      ],
      "edges": [
        42,
        43,
        30,
        24,
        40,
        44
      ]
    },
    {
      "id": 11,
      "axial": {
        "q": 0,
        "r": 2
      },
      "center": {
        "x": 103.92,
        "y": 180
      },
      "vertices": [
        35,
        36,
        37,
        23,
        22,
        34
      ],
      "edges": [
        45,
        46,
        47,
        27,
        43,
        48
      ]
    },
    {
      "id": 12,
      "axial": {
        "q": 1,
        "r": -2
      },
      "center": {
        "x": 0,
        "y": -180
      },
      "vertices": [
        38,
        39,
        29,
        26,
        25,
        40
      ],
      "edges": [
        49,
        50,
        38,
        31,
        51,
        52
      ]
    },
    {
      "id": 13,
      "axial": {
        "q": 1,
        "r": -1
      },
      "center": {
        "x": 51.96,
        "y": -90
      },
      "vertices": [
        41,
        42,
        31,
        30,
        29,
        39
      ],
      "edges": [
        53,
        54,
        41,
        36,
        50,
        55
      ]
    },
    {
      "id": 14,
      "axial": {
        "q": 1,
        "r": 0
      },
      "center": {
        "x": 103.92,
        "y": 0
      },
      "vertices": [
        43,
        44,
        33,
        32,
        31,
        42
      ],
      "edges": [
        56,
        57,
        44,
        39,
        54,
        58
      ]
    },
    {
      "id": 15,
      "axial": {
        "q": 1,
        "r": 1
      },
      "center": {
        "x": 155.88,
        "y": 90
      },
      "vertices": [
        45,
        46,
        35,
        34,
        33,
        44
      ],
      "edges": [
        59,
        60,
        48,
        42,
        57,
        61
      ]
    },
    {
      "id": 16,
      "axial": {
        "q": 2,
        "r": -2
      },
      "center": {
        "x": 103.92,
        "y": -180
      },
      "vertices": [
        47,
        48,
        41,
        39,
        38,
        49
      ],
      "edges": [
        62,
        63,
        55,
        49,
        64,
        65
      ]
    },
    {
      "id": 17,
      "axial": {
        "q": 2,
        "r": -1
      },
      "center": {
        "x": 155.88,
        "y": -90
      },
      "vertices": [
        50,
        51,
        43,
        42,
        41,
        48
      ],
      "edges": [
        66,
        67,
        58,
        53,
        63,
        68
      ]
    },
    {
      "id": 18,
      "axial": {
        "q": 2,
        "r": 0
      },
      "center": {
        "x": 207.85,
        "y": 0
      },
      "vertices": [
        52,
        53,
        45,
        44,
        43,
        51
      ],
      "edges": [
        69,
        70,
        61,
        56,
        67,
        71
      ]
    }
  ],
  "vertices": [
    {
      "id": 0,
      "pixel": {
        "x": -155.88,
        "y": -30
      },
      "tiles": [
        0,
        3,
        4
      ],
      "edges": [
        0,
        5,
        17
      ],
      "vertices": [
        1,
        5,
        15
      ]
    },
    {
      "id": 1,
      "pixel": {
        "x": -155.88,
        "y": 30
      },
      "tiles": [
        0,
        1,
        4
      ],
      "edges": [
        0,
        1,
        10
      ],
      "vertices": [
        0,
        2,
        6
      ]
    },
    {
      "id": 2,
      "pixel": {
        "x": -207.85,
        "y": 60
      },
      "tiles": [
        0,
        1
      ],
      "edges": [
        1,
        2,
        9
      ],
      "vertices": [
        1,
        3,
        9
      ]
    },
    {
      "id": 3,
      "pixel": {
        "x": -259.81,
        "y": 30
      },
      "tiles": [
        0
      ],
      "edges": [
        2,
        3
      ],
      "vertices": [
        2,
        4
      ]
    },
    {
      "id": 4,
      "pixel": {
        "x": -259.81,
        "y": -30
      },
      "tiles": [
        0
      ],
      "edges": [
        3,
        4
      ],
      "vertices": [
        3,
        5
      ]
    },
    {
      "id": 5,
      "pixel": {
        "x": -207.85,
        "y": -60
      },
      "tiles": [
        0,
        3
      ],
      "edges": [
        4,
        5,
        18
      ],
      "vertices": [
        0,
        4,
        16
      ]
    },
    {
      "id": 6,
      "pixel": {
        "x": -103.92,
        "y": 60
      },
      "tiles": [
        1,
        4,
        5
      ],
      "edges": [
        6,
        10,
        22
      ],
      "vertices": [
        1,
        7,
        19
      ]
    },
    {
      "id": 7,
      "pixel": {
        "x": -103.92,
        "y": 120
      },
      "tiles": [
        1,
        2,
        5
      ],
      "edges": [
        6,
        7,
        15
      ],
      "vertices": [
        6,
        8,
        10
      ]
    },
    {
      "id": 8,
      "pixel": {
        "x": -155.88,
        "y": 150
      },
      "tiles": [
        1,
        2
      ],
      "edges": [
        7,
        8,
        14
      ],
      "vertices": [
        7,
        9,
        13
      ]
    },
    {
      "id": 9,
      "pixel": {
        "x": -207.85,
        "y": 120
      },
      "tiles": [
        1
      ],
      "edges": [
        8,
        9
      ],
      "vertices": [
        2,
        8
      ]
    },
    {
      "id": 10,
      "pixel": {
        "x": -51.96,
        "y": 150
      },
      "tiles": [
        2,
        5,
        6
      ],
      "edges": [
        11,
        15,
        25
      ],
      "vertices": [
        7,
        11,
        21
      ]
    },
    {
      "id": 11,
      "pixel": {
        "x": -51.96,
        "y": 210
      },
      "tiles": [
        2,
        6
      ],
      "edges": [
        11,
        12,
        29
      ],
      "vertices": [
        10,
        12,
        24
      ]
    },
    {
      "id": 12,
      "pixel": {
        "x": -103.92,
        "y": 240
      },
      "tiles": [
        2
      ],
      "edges": [
        12,
        13
      ],
      "vertices": [
        11,
        13
      ]
    },
    {
      "id": 13,
      "pixel": {
        "x": -155.88,
        "y": 210
      },
      "tiles": [
        2
      ],
      "edges": [
        13,
        14
      ],
      "vertices": [
        8,
        12
      ]
    },
    {
      "id": 14,
      "pixel": {
        "x": -103.92,
        "y": -120
      },
      "tiles": [
        3,
        7,
        8
      ],
      "edges": [
        16,
        20,
        32
      ],
      "vertices": [
        15,
        17,
        26
      ]
    },
    {
      "id": 15,
      "pixel": {
        "x": -103.92,
        "y": -60
      },
      "tiles": [
        3,
        4,
        8
      ],
      "edges": [
        16,
        17,
        23
      ],
      "vertices": [
        0,
        14,
        18
      ]
    },
    {
      "id": 16,
      "pixel": {
        "x": -207.85,
        "y": -120
      },
      "tiles": [
        3
      ],
      "edges": [
        18,
        19
      ],
      "vertices": [
        5,
        17
      ]
    },
    {
      "id": 17,
      "pixel": {
        "x": -155.88,
        "y": -150
      },
      "tiles": [
        3,
        7
      ],
      "edges": [
        19,
        20,
        33
      ],
      "vertices": [
        14,
        16,
        27
      ]
    },
    {
      "id": 18,
      "pixel": {
        "x": -51.96,
        "y": -30
      },
      "tiles": [
        4,
        8,
        9
      ],
      "edges": [
        21,
        23,
        37
      ],
      "vertices": [
        15,
        19,
        30
      ]
    },
    {
      "id": 19,
      "pixel": {
        "x": -51.96,
        "y": 30
      },
      "tiles": [
        4,
        5,
        9
      ],
      "edges": [
        21,
        22,
        26
      ],
      "vertices": [
        6,
        18,
        20
      ]
    },
    {
      "id": 20,
      "pixel": {
        "x": 0,
        "y": 60
      },
      "tiles": [
        5,
        9,
        10
      ],
      "edges": [
        24,
        26,
        40
      ],
      "vertices": [
        19,
        21,
        32
      ]
    },
    {
      "id": 21,
      "pixel": {
        "x": 0,
        "y": 120
      },
      "tiles": [
        5,
        6,
        10
      ],
      "edges": [
        24,
        25,
        30
      ],
      "vertices": [
        10,
        20,
        22
      ]
    },
    {
      "id": 22,
      "pixel": {
        "x": 51.96,
        "y": 150
      },
      "tiles": [
        6,
        10,
        11
      ],
      "edges": [
        27,
        30,
        43
      ],
      "vertices": [
        21,
        23,
        34
      ]
    },
    {
      "id": 23,
      "pixel": {
        "x": 51.96,
        "y": 210
      },
      "tiles": [
        6,
        11
      ],
      "edges": [
        27,
        28,
        47
      ],
      "vertices": [
        22,
        24,
        37
      ]
    },
    {
      "id": 24,
      "pixel": {
        "x": 0,
        "y": 240
      },
      "tiles": [
        6
      ],
      "edges": [
        28,
        29
      ],
      "vertices": [
        11,
        23
      ]
    },
    {
      "id": 25,
      "pixel": {
        "x": -51.96,
        "y": -210
      },
      "tiles": [
        7,
        12
      ],
      "edges": [
        31,
        35,
        51
      ],
      "vertices": [
        26,
        28,
        40
      ]
    },
    {
      "id": 26,
      "pixel": {
        "x": -51.96,
        "y": -150
      },
      "tiles": [
        7,
        8,
        12
      ],
      "edges": [
        31,
        32,
        38
      ],
      "vertices": [
        14,
        25,
        29
      ]
    },
    {
      "id": 27,
      "pixel": {
        "x": -155.88,
        "y": -210
      },
      "tiles": [
        7
      ],
      "edges": [
        33,
        34
      ],
      "vertices": [
        17,
        28
      ]
    },
    {
      "id": 28,
      "pixel": {
        "x": -103.92,
        "y": -240
      },
      "tiles": [
        7
      ],
      "edges": [
        34,
        35
      ],
      "vertices": [
        25,
        27
      ]
    },
    {
      "id": 29,
      "pixel": {
        "x": 0,
        "y": -120
      },
      "tiles": [
        8,
        12,
        13
      ],
      "edges": [
        36,
        38,
        50
      ],
      "vertices": [
        26,
        30,
        39
      ]
    },
    {
      "id": 30,
      "pixel": {
        "x": 0,
        "y": -60
      },
      "tiles": [
        8,
        9,
        13
      ],
      "edges": [
        36,
        37,
        41
      ],
      "vertices": [
        18,
        29,
        31
      ]
    },
    {
      "id": 31,
      "pixel": {
        "x": 51.96,
        "y": -30
      },
      "tiles": [
        9,
        13,
        14
      ],
      "edges": [
        39,
        41,
        54
      ],
      "vertices": [
        30,
        32,
        42
      ]
    },
    {
      "id": 32,
      "pixel": {
        "x": 51.96,
        "y": 30
      },
      "tiles": [
        9,
        10,
        14
      ],
      "edges": [
        39,
        40,
        44
      ],
      "vertices": [
        20,
        31,
        33
      ]
    },
    {
      "id": 33,
      "pixel": {
        "x": 103.92,
        "y": 60
      },
      "tiles": [
        10,
        14,
        15
      ],
      "edges": [
        42,
        44,
        57
      ],
      "vertices": [
        32,
        34,
        44
      ]
    },
    {
      "id": 34,
      "pixel": {
        "x": 103.92,
        "y": 120
      },
      "tiles": [
        10,
        11,
        15
      ],
      "edges": [
        42,
        43,
        48
      ],
      "vertices": [
        22,
        33,
        35
      ]
    },
    {
      "id": 35,
      "pixel": {
        "x": 155.88,
        "y": 150
      },
      "tiles": [
        11,
        15
      ],
      "edges": [
        45,
        48,
        60
      ],
      "vertices": [
        34,
        36,
        46
      ]
    },
    {
      "id": 36,
      "pixel": {
        "x": 155.88,
        "y": 210
      },
      "tiles": [
        11
      ],
      "edges": [
        45,
        46
      ],
      "vertices": [
        35,
        37
      ]
    },
    {
      "id": 37,
      "pixel": {
        "x": 103.92,
        "y": 240
      },
      "tiles": [
        11
      ],
      "edges": [
        46,
        47
      ],
      "vertices": [
        23,
        36
      ]
    },
    {
      "id": 38,
      "pixel": {
        "x": 51.96,
        "y": -210
      },
      "tiles": [
        12,
        16
      ],
      "edges": [
        49,
        52,
        64
      ],
      "vertices": [
        39,
        40,
        49
      ]
    },
    {
      "id": 39,
      "pixel": {
        "x": 51.96,
        "y": -150
      },
      "tiles": [
        12,
        13,
        16
      ],
      "edges": [
        49,
        50,
        55
      ],
      "vertices": [
        29,
        38,
        41
      ]
    },
    {
      "id": 40,
      "pixel": {
        "x": 0,
        "y": -240
      },
      "tiles": [
        12
      ],
      "edges": [
        51,
        52
      ],
      "vertices": [
        25,
        38
      ]
    },
    {
      "id": 41,
      "pixel": {
        "x": 103.92,
        "y": -120
      },
      "tiles": [
        13,
        16,
        17
      ],
      "edges": [
        53,
        55,
        63
      ],
      "vertices": [
        39,
        42,
        48
      ]
    },
    {
      "id": 42,
      "pixel": {
        "x": 103.92,
        "y": -60
      },
      "tiles": [
        13,
        14,
        17
      ],
      "edges": [
        53,
        54,
        58
      ],
      "vertices": [
        31,
        41,
        43
      ]
    },
    {
      "id": 43,
      "pixel": {
        "x": 155.88,
        "y": -30
      },
      "tiles": [
        14,
        17,
        18
      ],
      "edges": [
        56,
        58,
        67
      ],
      "vertices": [
        42,
        44,
        51
      ]
    },
    {
      "id": 44,
      "pixel": {
        "x": 155.88,
        "y": 30
      },
      "tiles": [
        14,
        15,
        18
      ],
      "edges": [
        56,
        57,
        61
      ],
      "vertices": [
        33,
        43,
        45
      ]
    },
    {
      "id": 45,
      "pixel": {
        "x": 207.85,
        "y": 60
      },
      "tiles": [
        15,
        18
      ],
      "edges": [
        59,
        61,
        70
      ],
      "vertices": [
        44,
        46,
        53
      ]
    },
    {
      "id": 46,
      "pixel": {
        "x": 207.85,
        "y": 120
      },
      "tiles": [
        15
      ],
      "edges": [
        59,
        60
      ],
      "vertices": [
        35,
        45
      ]
    },
    {
      "id": 47,
      "pixel": {
        "x": 155.88,
        "y": -210
      },
      "tiles": [
        16
      ],
      "edges": [
        62,
        65
      ],
      "vertices": [
        48,
        49
      ]
    },
    {
      "id": 48,
      "pixel": {
        "x": 155.88,
        "y": -150
      },
      "tiles": [
        16,
        17
      ],
      "edges": [
        62,
        63,
        68
      ],
      "vertices": [
        41,
        47,
        50
      ]
    },
    {
      "id": 49,
      "pixel": {
        "x": 103.92,
        "y": -240
      },
      "tiles": [
        16
      ],
      "edges": [
        64,
        65
      ],
      "vertices": [
        38,
        47
      ]
    },
    {
      "id": 50,
      "pixel": {
        "x": 207.85,
        "y": -120
      },
      "tiles": [
        17
      ],
      "edges": [
        66,
        68
      ],
      "vertices": [
        48,
        51
      ]
    },
    {
      "id": 51,
      "pixel": {
        "x": 207.85,
        "y": -60
      },
      "tiles": [
        17,
        18
      ],
      "edges": [
        66,
        67,
        71
      ],
      "vertices": [
        43,
        50,
        52
      ]
    },
    {
      "id": 52,
      "pixel": {
        "x": 259.81,
        "y": -30
      },
      "tiles": [
        18
      ],
      "edges": [
        69,
        71
      ],
      "vertices": [
        51,
        53
      ]
    },
    {
      "id": 53,
      "pixel": {
        "x": 259.81,
        "y": 30
      },
      "tiles": [
        18
      ],
      "edges": [
        69,
        70
      ],
      "vertices": [
        45,
        52
      ]
    }
  ],
  "edges": [
    {
      "id": 0,
      "vertices": [
        0,
        1
      ],
      "tiles": [
        0,
        4
      ]
    },
    {
      "id": 1,
      "vertices": [
        1,
        2
      ],
      "tiles": [
        0,
        1
      ]
    },
    {
      "id": 2,
      "vertices": [
        2,
        3
      ],
      "tiles": [
        0
      ]
    },
    {
      "id": 3,
      "vertices": [
        3,
        4
      ],
      "tiles": [
        0
      ]
    },
    {
      "id": 4,
      "vertices": [
        4,
        5
      ],
      "tiles": [
        0
      ]
    },
    {
      "id": 5,
      "vertices": [
        0,
        5
      ],
      "tiles": [
        0,
        3
      ]
    },
    {
      "id": 6,
      "vertices": [
        6,
        7
      ],
      "tiles": [
        1,
        5
      ]
    },
    {
      "id": 7,
      "vertices": [
        7,
        8
      ],
      "tiles": [
        1,
        2
      ]
    },
    {
      "id": 8,
      "vertices": [
        8,
        9
      ],
      "tiles": [
        1
      ]
    },
    {
      "id": 9,
      "vertices": [
        2,
        9
      ],
      "tiles": [
        1
      ]
    },
    {
      "id": 10,
      "vertices": [
        1,
        6
      ],
      "tiles": [
        1,
        4
      ]
    },
    {
      "id": 11,
      "vertices": [
        10,
        11
      ],
      "tiles": [
        2,
        6
      ]
    },
    {
      "id": 12,
      "vertices": [
        11,
        12
      ],
      "tiles": [
        2
      ]
    },
    {
      "id": 13,
      "vertices": [
        12,
        13
      ],
      "tiles": [
        2
      ]
    },
    {
      "id": 14,
      "vertices": [
        8,
        13
      ],
      "tiles": [
        2
      ]
    },
    {
      "id": 15,
      "vertices": [
        7,
        10
      ],
      "tiles": [
        2,
        5
      ]
    },
    {
      "id": 16,
      "vertices": [
        14,
        15
      ],
      "tiles": [
        3,
        8
      ]
    },
    {
      "id": 17,
      "vertices": [
        0,
        15
      ],
      "tiles": [
        3,
        4
      ]
    },
    {
      "id": 18,
      "vertices": [
        5,
        16
      ],
      "tiles": [
        3
      ]
    },
    {
      "id": 19,
      "vertices": [
        16,
        17
      ],
      "tiles": [
        3
      ]
    },
    {
      "id": 20,
      "vertices": [
        14,
        17
      ],
      "tiles": [
        3,
        7
      ]
    },
    {
      "id": 21,
      "vertices": [
        18,
        19
      ],
      "tiles": [
        4,
        9
      ]
    },
    {
      "id": 22,
      "vertices": [
        6,
        19
      ],
      "tiles": [
        4,
        5
      ]
    },
    {
      "id": 23,
      "vertices": [
        15,
        18
      ],
      "tiles": [
        4,
        8
      ]
    },
    {
      "id": 24,
      "vertices": [
        20,
        21
      ],
      "tiles": [
        5,
        10
      ]
    },
    {
      "id": 25,
      "vertices": [
        10,
        21
      ],
      "tiles": [
        5,
        6
      ]
    },
    {
      "id": 26,
      "vertices": [
        19,
        20
      ],
      "tiles": [
        5,
        9
      ]
    },
    {
      "id": 27,
      "vertices": [
        22,
        23
      ],
      "tiles": [
        6,
        11
      ]
    },
    {
      "id": 28,
      "vertices": [
        23,
        24
      ],
      "tiles": [
        6
      ]
    },
    {
      "id": 29,
      "vertices": [
        11,
        24
      ],
      "tiles": [
        6
      ]
    },
    {
      "id": 30,
      "vertices": [
        21,
        22
      ],
      "tiles": [
        6,
        10
      ]
    },
    {
      "id": 31,
      "vertices": [
        25,
        26
      ],
      "tiles": [
        7,
        12
      ]
    },
    {
      "id": 32,
      "vertices": [
        14,
        26
      ],
      "tiles": [
        7,
        8
      ]
    },
    {
      "id": 33,
      "vertices": [
        17,
        27
      ],
      "tiles": [
        7
      ]
    },
    {
      "id": 34,
      "vertices": [
        27,
        28
      ],
      "tiles": [
        7
      ]
    },
    {
      "id": 35,
      "vertices": [
        25,
        28
      ],
      "tiles": [
        7
      ]
    },
    {
      "id": 36,
      "vertices": [
        29,
        30
      ],
      "tiles": [
        8,
        13
      ]
    },
    {
      "id": 37,
      "vertices": [
        18,
        30
      ],
      "tiles": [
        8,
        9
      ]
    },
    {
      "id": 38,
      "vertices": [
        26,
        29
      ],
      "tiles": [
        8,
        12
      ]
    },
    {
      "id": 39,
      "vertices": [
        31,
        32
      ],
      "tiles": [
        9,
        14
      ]
    },
    {
      "id": 40,
      "vertices": [
        20,
        32
      ],
      "tiles": [
        9,
        10
      ]
    },
    {
      "id": 41,
      "vertices": [
        30,
        31
      ],
      "tiles": [
        9,
        13
      ]
    },
    {
      "id": 42,
      "vertices": [
        33,
        34
      ],
      "tiles": [
        10,
        15
      ]
    },
    {
      "id": 43,
      "vertices": [
        22,
        34
      ],
      "tiles": [
        10,
        11
      ]
    },
    {
      "id": 44,
      "vertices": [
        32,
        33
      ],
      "tiles": [
        10,
        14
      ]
    },
    {
      "id": 45,
      "vertices": [
        35,
        36
      ],
      "tiles": [
        11
      ]
    },
    {
      "id": 46,
      "vertices": [
        36,
        37
      ],
      "tiles": [
        11
      ]
    },
    {
      "id": 47,
      "vertices": [
        23,
        37
      ],
      "tiles": [
        11
      ]
    },
    {
      "id": 48,
      "vertices": [
        34,
        35
      ],
      "tiles": [
        11,
        15
      ]
    },
    {
      "id": 49,
      "vertices": [
        38,
        39
      ],
      "tiles": [
        12,
        16
      ]
    },
    {
      "id": 50,
      "vertices": [
        29,
        39
      ],
      "tiles": [
        12,
        13
      ]
    },
    {
      "id": 51,
      "vertices": [
        25,
        40
      ],
      "tiles": [
        12
      ]
    },
    {
      "id": 52,
      "vertices": [
        38,
        40
      ],
      "tiles": [
        12
      ]
    },
    {
      "id": 53,
      "vertices": [
        41,
        42
      ],
      "tiles": [
        13,
        17
      ]
    },
    {
      "id": 54,
      "vertices": [
        31,
        42
      ],
      "tiles": [
        13,
        14
      ]
    },
    {
      "id": 55,
      "vertices": [
        39,
        41
      ],
      "tiles": [
        13,
        16
      ]
    },
    {
      "id": 56,
      "vertices": [
        43,
        44
      ],
      "tiles": [
        14,
        18
      ]
    },
    {
      "id": 57,
      "vertices": [
        33,
        44
      ],
      "tiles": [
        14,
        15
      ]
    },
    {
      "id": 58,
      "vertices": [
        42,
        43
      ],
      "tiles": [
        14,
        17
      ]
    },
    {
      "id": 59,
      "vertices": [
        45,
        46
      ],
      "tiles": [
        15
      ]
    },
    {
      "id": 60,
      "vertices": [
        35,
        46
      ],
      "tiles": [
        15
      ]
    },
    {
      "id": 61,
      "vertices": [
        44,
        45
      ],
      "tiles": [
        15,
        18
      ]
    },
    {
      "id": 62,
      "vertices": [
        47,
        48
      ],
      "tiles": [
        16
      ]
    },
    {
      "id": 63,
      "vertices": [
        41,
        48
      ],
      "tiles": [
        16,
        17
      ]
    },
    {
      "id": 64,
      "vertices": [
        38,
        49
      ],
      "tiles": [
        16
      ]
    },
    {
      "id": 65,
      "vertices": [
        47,
        49
      ],
      "tiles": [
        16
      ]
    },
    {
      "id": 66,
      "vertices": [
        50,
        51
      ],
      "tiles": [
        17
      ]
    },
    {
      "id": 67,
      "vertices": [
        43,
        51
      ],
      "tiles": [
        17,
        18
      ]
    },
    {
      "id": 68,
      "vertices": [
        48,
        50
      ],
      "tiles": [
        17
      ]
    },
    {
      "id": 69,
      "vertices": [
        52,
        53
      ],
      "tiles": [
        18
      ]
    },
    {
      "id": 70,
      "vertices": [
        45,
        53
      ],
      "tiles": [
        18
      ]
    },
    {
      "id": 71,
      "vertices": [
        51,
        52
      ],
      "tiles": [
        18
      ]
    }
  ],
  "ports": [
    {
      "id": 0,
      "vertices": [
        2,
        3
      ],
      "pixel": {
        "x": -261.33,
        "y": 50.29
      }
    },
    {
      "id": 1,
      "vertices": [
        5,
        16
      ],
      "pixel": {
        "x": -233.54,
        "y": -101.13
      }
    },
    {
      "id": 2,
      "vertices": [
        27,
        28
      ],
      "pixel": {
        "x": -143.9,
        "y": -249.25
      }
    },
    {
      "id": 3,
      "vertices": [
        38,
        49
      ],
      "pixel": {
        "x": 87.1,
        "y": -251.46
      }
    },
    {
      "id": 4,
      "vertices": [
        48,
        50
      ],
      "pixel": {
        "x": 204.35,
        "y": -151.69
      }
    },
    {
      "id": 5,
      "vertices": [
        52,
        53
      ],
      "pixel": {
        "x": 287.81,
        "y": 0
      }
    },
    {
      "id": 6,
      "vertices": [
        35,
        36
      ],
      "pixel": {
        "x": 174.21,
        "y": 201.17
      }
    },
    {
      "id": 7,
      "vertices": [
        23,
        24
      ],
      "pixel": {
        "x": 29.19,
        "y": 252.82
      }
    },
    {
      "id": 8,
      "vertices": [
        12,
        13
      ],
      "pixel": {
        "x": -143.9,
        "y": 249.25
      }
    }
  ]
};
