/**
 * Offline freezer: runs the hex-math generator once and writes its output to
 * `src/board/board.data.ts` as a committed constant. Run via `npm run
 * freeze-board` in the shared package. The runtime never calls the generator —
 * it imports the frozen data — so a future generator change cannot silently
 * shift the board out from under the rules. Re-run deliberately, then re-verify.
 */

import { writeFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { dirname, join } from 'node:path';
import { generateBoardTopology } from '../src/board/generate.js';

const board = generateBoardTopology();
const here = dirname(fileURLToPath(import.meta.url));
const out = join(here, '..', 'src', 'board', 'board.data.ts');

const banner = `/**
 * FROZEN BASE-GAME BOARD TOPOLOGY — generated by scripts/freeze-board.ts.
 * Do not edit by hand. Regenerate with \`npm run freeze-board\` (shared package),
 * then re-run the verification tests before trusting the result.
 */
import type { BoardTopology } from './types.js';

export const BOARD_DATA: BoardTopology = `;

writeFileSync(out, `${banner}${JSON.stringify(board, null, 2)};\n`, 'utf8');
console.log(`Wrote frozen board to ${out}`);
